### ISSUE TITLE
Support for Ladder Diagram

### ISSUE THREAD

**Issue by MVS-99** [jubnzv/IEC.vim#4]
Is there plans to support Ladder Diagrams programming for transitions of SFC?

**Comment by jubnzv** [comment]
Hi @MVS-99 ,
LD is a graphical language, therefore it is not possible to edit it in a text editor. But some IDEs use XML to represent it, so you can use any XML plugin in vim to work with it.

**Comment by MVS-99** [comment]
> Hi @MVS-99 , LD is a graphical language, therefore it is not possible to edit it in a text editor. But some IDEs use XML to represent it, so you can use any XML plugin in vim to work with it.

It would be very interesting to see if I may be capable of doing so. I hope that you get feedback from me in the future with this matter!
